[package]
name = "hd_fpv_osd_font_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-macro = "2.1.5"
clap = { version = "4.0.18", features = ["derive"] }
close-err = "1.0.1"
derive_more = "0.99.17"
error-stack = "0.2.3"
image = { version = "0.24.4", features = ["rgb"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
strum = { version = "0.24.1", features = ["derive"] }
